name: Publish Docker Image

on:
  push:
    branches:
      - "develop"
      - "release/v*"

jobs:
  push:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-20.04
    # Always run against a tag, even if the commit into the tag has [docker skip]
    # within the commit message.
    if: "!contains(github.ref, 'develop') || (!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip'))"
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Docker Metadata
        uses: docker/metadata-action@v4
        id: docker_meta
        with:
          images: ghcr.io/pterodactyl/panel

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Release production build
        uses: docker/build-push-action@v2
        if: "contains(github.ref, 'release/v')"
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Release development build
        uses: docker/build-push-action@v2
        if: "contains(github.ref, 'develop')"
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
